In [1]:
import numpy as np

In [3]:
arr1=np.arange(1,40,2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [4]:
# Reshape array to matrix of size 4X5
arr2=arr1.reshape(4,5)
print(arr2)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [9]:
# Reshape array without determining the column size BY USING -1
arr3=arr2.reshape(5,-1)
print(arr3)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]


In [10]:
# Transpose a numpy array
arr4=arr3.T
print(arr4)

[[ 1  9 17 25 33]
 [ 3 11 19 27 35]
 [ 5 13 21 29 37]
 [ 7 15 23 31 39]]


In [27]:
# Stack 2 arrays vertically on top of each other, NUMBER OF COLUMNS SHOULD BE SAME FOR THIS
ar1=np.arange(1,31).reshape(5,6)
ar2=np.random.randint(1,20,42).reshape(7,6)
ar3=np.vstack((ar1,ar2))
print(ar1,"\n\n",ar2,"\n\nVSTACKED::::::\n")
print(ar3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 

 [[11  4 18 13 15  8]
 [14  3 19 17 16  5]
 [ 1 19 19 11  5 16]
 [ 6 11  9  5 14  3]
 [ 6 11  2  8 11 11]
 [14 12 13  2 10  2]
 [ 2 13 13  4  1  4]] 

VSTACKED::::::

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [11  4 18 13 15  8]
 [14  3 19 17 16  5]
 [ 1 19 19 11  5 16]
 [ 6 11  9  5 14  3]
 [ 6 11  2  8 11 11]
 [14 12 13  2 10  2]
 [ 2 13 13  4  1  4]]


In [29]:
# Stack 2 arrays horizontally one beside other, NUMBER OF ROWS SHOULD BE SAME FOR THIS
ar1=np.arange(1,31).reshape(5,6)
ar2=np.random.randint(1,20,40).reshape(5,8)
ar3=np.hstack((ar1,ar2))
print(ar1,"\n\n",ar2,"\n\nHSTACKED::::::\n")
print(ar3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 

 [[ 9  2  3  6 13 10 12 14]
 [17  2  3  3  2 10 10 19]
 [ 9  2 17  3  5  4 18 12]
 [ 6  9 12  9  3 14 15 17]
 [14  4 14  9 15  7 13 16]] 

HSTACKED::::::

[[ 1  2  3  4  5  6  9  2  3  6 13 10 12 14]
 [ 7  8  9 10 11 12 17  2  3  3  2 10 10 19]
 [13 14 15 16 17 18  9  2 17  3  5  4 18 12]
 [19 20 21 22 23 24  6  9 12  9  3 14 15 17]
 [25 26 27 28 29 30 14  4 14  9 15  7 13 16]]


In [33]:
# Numpy basic math functions - exp, sin, cos, log, sqrt
print("EXP:\t",np.exp(arr1),"\n")
print("SIN:\t",np.sin(arr1),"\n")
print("COS:\t",np.cos(arr1),"\n")
print("LOG:\t",np.log(arr1),"\n")
print("SQRT:\t",np.sqrt(arr1),"\n")

EXP:	 [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03 5.98741417e+04 4.42413392e+05 3.26901737e+06
 2.41549528e+07 1.78482301e+08 1.31881573e+09 9.74480345e+09
 7.20048993e+10 5.32048241e+11 3.93133430e+12 2.90488497e+13
 2.14643580e+14 1.58601345e+15 1.17191424e+16 8.65934004e+16] 

SIN:	 [ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849 -0.99999021
  0.42016704  0.65028784 -0.96139749  0.14987721  0.83665564 -0.8462204
 -0.13235175  0.95637593 -0.66363388 -0.40403765  0.99991186 -0.42818267
 -0.64353813  0.96379539] 

COS:	 [ 0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026  0.0044257
  0.90744678 -0.75968791 -0.27516334  0.98870462 -0.54772926 -0.53283302
  0.99120281 -0.29213881 -0.74805753  0.91474236 -0.01327675 -0.90369221
  0.76541405  0.26664293] 

LOG:	 [0.         1.09861229 1.60943791 1.94591015 2.19722458 2.39789527
 2.56494936 2.7080502  2.83321334 2.94443898 3.04452244 3.13549422
 3.21887582 3.29583687 3.36729583 3.433987

In [39]:
# Apply custom function on numpy array
f=np.vectorize(lambda x:x**3)
f(arr1)

array([    1,    27,   125,   343,   729,  1331,  2197,  3375,  4913,
        6859,  9261, 12167, 15625, 19683, 24389, 29791, 35937, 42875,
       50653, 59319])

In [46]:
# Get linear algebra operations done on numpy matrix using NUMPY.LINALG
print("INVERSE:\n",np.linalg.inv(arr1[1:10].reshape(3,3)),"\n\n")
print("DETERMINANT:\t",np.linalg.det(arr1[1:10].reshape(3,3)),"\n\n")
print("EIGENVALUES:\n",np.linalg.eig(arr1[1:10].reshape(3,3))[0],"\n\nEIGENVECTORS:\n",np.linalg.eig(arr1[1:10].reshape(3,3))[1])

INVERSE:
 [[ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]
 [-5.62949953e+14  1.12589991e+15 -5.62949953e+14]
 [ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]] 


DETERMINANT:	 -4.263256414560604e-14 


EIGENVALUES:
 [ 3.50539753e+01 -2.05397532e+00  2.82533269e-16] 

EIGENVECTORS:
 [[-0.25903829 -0.78021202  0.40824829]
 [-0.53244605 -0.07991115 -0.81649658]
 [-0.80585381  0.62038972  0.40824829]]


In [48]:
# Multiply numpy matrices using dot product
m1=np.arange(30).reshape(5,6)
m2=np.arange(30).reshape(6,5)
print(np.dot(m1,m2))

[[ 275  290  305  320  335]
 [ 725  776  827  878  929]
 [1175 1262 1349 1436 1523]
 [1625 1748 1871 1994 2117]
 [2075 2234 2393 2552 2711]]
