Q. Write a function to generate N samples from a normal distribution and plot them on the histogram.

In [1]:
import numpy as np

In [2]:
arr1=np.array([2,3,4,5])
arr2=np.array([6,7,8,9])
print(arr1,arr2)

[2 3 4 5] [6 7 8 9]


In [4]:
# Multiplying two numpy array together BY NOT USING FOR LOOP
mul=arr1*arr2
print(mul)

[12 21 32 45]


In [5]:
# Square each element in numpy array WITHOUT USING FOR LOOP and then multiply the two arrays
sq=(arr1**2)*(arr2**2)
print(sq)

[ 144  441 1024 2025]


In [6]:
# Create a numpy matrix of 4X3 of data type int FILLED WITH ONES
ones=np.ones([4,3],int)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
# Create a numpy matrix of 5X6 of data type int FILLED WITH ZEROS
zeros=np.zeros([5,6],int)
print(zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [12]:
# Create a random matrix of size 6X5
randm=np.random.random([6,5])
print(randm)

[[0.28001125 0.396052   0.84317374 0.7098223  0.77091889]
 [0.12626861 0.81645426 0.6528869  0.2298444  0.7509116 ]
 [0.01430199 0.03514867 0.14404292 0.73469109 0.81284714]
 [0.14736307 0.12846315 0.92859279 0.10655547 0.9345796 ]
 [0.07304237 0.04125108 0.11855047 0.33447557 0.93951112]
 [0.35713156 0.07924321 0.4216223  0.75329779 0.87362849]]


In [13]:
# Create a 10X10 matrix ranging from 50 to 1000 of step size 20
rang=np.arange(50,1000,20)
print(rang)

[ 50  70  90 110 130 150 170 190 210 230 250 270 290 310 330 350 370 390
 410 430 450 470 490 510 530 550 570 590 610 630 650 670 690 710 730 750
 770 790 810 830 850 870 890 910 930 950 970 990]


In [51]:
# Create an array of 50 numbers starting from 1 to 500 without determining the step size of the range
linsp=np.linspace(1,500,50)
print(linsp)

[  1.          11.18367347  21.36734694  31.55102041  41.73469388
  51.91836735  62.10204082  72.28571429  82.46938776  92.65306122
 102.83673469 113.02040816 123.20408163 133.3877551  143.57142857
 153.75510204 163.93877551 174.12244898 184.30612245 194.48979592
 204.67346939 214.85714286 225.04081633 235.2244898  245.40816327
 255.59183673 265.7755102  275.95918367 286.14285714 296.32653061
 306.51020408 316.69387755 326.87755102 337.06122449 347.24489796
 357.42857143 367.6122449  377.79591837 387.97959184 398.16326531
 408.34693878 418.53061224 428.71428571 438.89795918 449.08163265
 459.26530612 469.44897959 479.63265306 489.81632653 500.        ]


In [17]:
# Create a constant array of any number N
con=np.full([8,6],9)
print(con)

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [20]:
# Create 5X3 tile of arrays in a separate array 
tile=np.tile([10,20,30],[5,3])
print(tile)

[[10 20 30 10 20 30 10 20 30]
 [10 20 30 10 20 30 10 20 30]
 [10 20 30 10 20 30 10 20 30]
 [10 20 30 10 20 30 10 20 30]
 [10 20 30 10 20 30 10 20 30]]


In [24]:
# Create an identity matrix of size 3X3
eye=np.eye(3,dtype=int)
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [26]:
# Create a random array of integers within 10 and 20 of size 3X3
rndint=np.random.randint(10,20,[3,3])
print(rndint)

[[11 12 12]
 [14 13 12]
 [14 19 15]]


In [40]:
# Get shape shape, dtype, ndim and itemsize of array
print("Array:\t",randm,"\n")
print("Shape: ",randm.shape,"\t","Type: ",randm.dtype,"\t","Dimensions: ",randm.ndim,"\t","Item Size: ",randm.itemsize)

Array:	 [[0.28001125 0.396052   0.84317374 0.7098223  0.77091889]
 [0.12626861 0.81645426 0.6528869  0.2298444  0.7509116 ]
 [0.01430199 0.03514867 0.14404292 0.73469109 0.81284714]
 [0.14736307 0.12846315 0.92859279 0.10655547 0.9345796 ]
 [0.07304237 0.04125108 0.11855047 0.33447557 0.93951112]
 [0.35713156 0.07924321 0.4216223  0.75329779 0.87362849]] 

Shape:  (6, 5) 	 Type:  float64 	 Dimensions:  2 	 Item Size:  8


In [64]:
# SLICING AND INDEXING in numpy arrays
print(f"Print the 4th element in array\t{sq}:\t{sq[3]}\n")

print(f"Get only 2nd 3rd 4th element:\t{rang[[1,2,3]]}\n")

print(f"Get first3 and last3:\t{rang[0:3]}\t{rang[len(rang)-3:]}\n")

print(f"Get subset of values at increment of 5 starting from 0:\t{rang[0::5]}")

print(f"Get the 3rd row 2nd element in array:\t{randm[2,1]}")

Print the 4th element in array	[ 144  441 1024 2025]:	2025

Get only 2nd 3rd 4th element:	[ 70  90 110]

Get first3 and last3:	[50 70 90]	[950 970 990]

Get subset of values at increment of 5 starting from 0:	[ 50 150 250 350 450 550 650 750 850 950]
Get the 3rd row 2nd element in array:	0.03514867397003607
